apiVersion: v2
appVersion: v1.8.3
description: A Helm chart for Argo Rollouts
name: argo-rollouts
version: 2.40.5
home: https://github.com/argoproj/argo-helm
icon: https://argoproj.github.io/argo-rollouts/assets/logo.png
keywords:
  - argoproj
  - argo-rollouts
sources:
  - https://github.com/argoproj/argo-rollouts
maintainers:
  - name: argoproj
    url: https://argoproj.github.io/
annotations:
  artifacthub.io/signKey: |
    fingerprint: 2B8F22F57260EFA67BE1C5824B11F800CD9D2252
    url: https://argoproj.github.io/argo-helm/pgp_keys.asc
  artifacthub.io/changes: |
    - kind: changed
      description: use named port for service
