apiVersion: v1
appVersion: "0.7"
description: A Helm chart for Argo Rollouts
name: argo-rollouts
version: 0.2.0
icon: https://raw.githubusercontent.com/argoproj/argo/master/argo.png
home: https://github.com/argoproj/argo-helm
maintainers:
  - name: alexmt
  - name: dthomson25
  - name: jessesuen
