apiVersion: v2
appVersion: "v1.2.0"
description: A Helm chart for Argo Rollouts
name: argo-rollouts
version: 2.19.0
icon: https://argoproj.github.io/argo-rollouts/assets/logo.png
home: https://github.com/argoproj/argo-helm
maintainers:
  - name: alexmt
  - name: dthomson25
  - name: jessesuen
annotations:
  artifacthub.io/changes: |
    - "[Added]: initContainer option to controller pod, updated secrets roles"
