apiVersion: v2
appVersion: v1.3.1
description: A Helm chart for Argo Rollouts
name: argo-rollouts
version: 2.21.2
home: https://github.com/argoproj/argo-helm
icon: https://argoproj.github.io/argo-rollouts/assets/logo.png
keywords:
  - argoproj
  - argo-rollouts
sources:
  - https://github.com/argoproj/argo-rollouts
maintainers:
  - name: argoproj
    url: https://argoproj.github.io/
annotations:
  artifacthub.io/changes: |
    - "[Changed]: avoid app.kubernetes.io/version kubernetes label from exceeding maximum length (63)
