apiVersion: v2
appVersion: v1.2.1
description: A Helm chart for ArgoCD notifications, an add-on to ArgoCD.
name: argocd-notifications
type: application
version: 1.9.0
home: https://github.com/argoproj/argo-helm
icon: https://argocd-notifications.readthedocs.io/en/stable/assets/logo.png
keywords:
  - argoproj
  - argocd
  - argocd-notifications
maintainers:
  - name: alexmt
  - name: andyfeller
annotations:
  artifacthub.io/changes: |
    - "[Added]: Ability to define custom env variables for ArgoCD applicationset"
