apiVersion: v2
appVersion: 1.1.1
description: A Helm chart for ArgoCD notifications, an add-on to ArgoCD.
name: argocd-notifications
type: application
version: 1.4.1
home: https://github.com/argoproj/argo-helm
icon: https://raw.githubusercontent.com/argoproj/argo/master/docs/assets/argo.png
keywords:
  - argoproj
  - argocd
  - argocd-notifications
maintainers:
  - name: alexmt
  - name: andyfeller
annotations:
  artifacthub.io/changes: |
    - "[Added]: Initialize Changelog"
