{{- if .Values.server.configEnabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  labels:
    {{- include "argo-cd.labels" (dict "context" . "component" .Values.server.name "name" "cm") | nindent 4 }}
  {{- if .Values.server.configAnnotations }}
  annotations:
  {{- range $key, $value := .Values.server.configAnnotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
data: {{- include "argo-cd.config" $ | nindent 4 }}
{{- end }}