apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  labels:
    app.kubernetes.io/name: {{ include "argo-cd.name" . }}-rbac-cm
    helm.sh/chart: {{ include "argo-cd.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/component: {{ .Values.server.name }}
  {{- if .Values.server.rbacConfigAnnotations }}
  annotations:
  {{- range $key, $value := .Values.server.rbacConfigAnnotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
{{- if .Values.server.rbacConfig }}
data:
{{- toYaml .Values.server.rbacConfig | nindent 4 }}
{{- end }}