{{- if and (or .Values.externalRedis.username .Values.externalRedis.password) (not .Values.externalRedis.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "argo-cd.redis.fullname" . }}
  labels:
    {{- include "argo-cd.labels" (dict "context" $) | nindent 4 }}
  {{- with .Values.externalRedis.secretAnnotations }}
  annotations:
    {{- toYaml . | nindent 4}}
  {{- end }}
type: Opaque
data:
{{- if .Values.externalRedis.username }}
  redis-username: {{ .Values.externalRedis.username | b64enc }}
{{- end }}
{{- if .Values.externalRedis.password }}
  redis-password: {{ .Values.externalRedis.password | b64enc }}
{{- end }}
{{- end }}