apiVersion: v1
appVersion: v2.8.0
description: A Helm chart for Argo Workflows
name: argo
version: 0.11.0
icon: https://raw.githubusercontent.com/argoproj/argo/master/docs/assets/argo.png
home: https://github.com/argoproj/argo-helm
maintainers:
  - name: alexec
  - name: alexmt
  - name: jessesuen
  - name: benjaminws
