apiVersion: v1
appVersion: "v2.4.3"
description: A Helm chart for Argo Workflows
name: argo
version: 0.6.4
icon: https://raw.githubusercontent.com/argoproj/argo/master/argo.png
home: https://github.com/argoproj/argo-helm
maintainers:
  - name: alexec
  - name: alexmt
  - name: jessesuen
  - name: benjaminws
