apiVersion: v1
appVersion: v2.7.2
description: A Helm chart for Argo Workflows
name: argo
version: 0.7.6
icon: https://raw.githubusercontent.com/argoproj/argo/master/docs/assets/argo.png
home: https://github.com/argoproj/argo-helm
maintainers:
  - name: alexec
  - name: alexmt
  - name: jessesuen
  - name: benjaminws
