apiVersion: v2
appVersion: v2.12.3
description: A Helm chart for Argo Workflows
name: argo
version: 0.15.2
icon: https://raw.githubusercontent.com/argoproj/argo/master/docs/assets/argo.png
home: https://github.com/argoproj/argo-helm
maintainers:
  - name: alexec
  - name: alexmt
  - name: jessesuen
  - name: benjaminws
dependencies:
- name: minio
  version: 8.0.9
  repository: https://helm.min.io/
  condition: minio.install
