{{- if .Values.controller.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "argo-cd.controller.fullname" . }}
  labels:
    release: {{ .Release.Name }}
    app.kubernetes.io/name: {{ include "argo-cd.name" . }}-{{ .Values.controller.name }}
    helm.sh/chart: {{ include "argo-cd.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: {{ include "argo-cd.name" . }}
    app.kubernetes.io/component: {{ .Values.controller.name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "argo-cd.controller.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "argo-cd.controllerServiceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}