# Test with extraObjects enabled

crds:
  # Delete CRDs upon uninstall, otherwise they would conflict with other tests
  keep: false

extraObjects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: datadog
    type: Opaque
    data:
      address: aHR0cHM6Ly9hcGkuZGF0YWRvZ2hxLmNvbQo= # https://api.datadoghq.com
      api-key: dGVzdC1hcGkta2V5Cg== # test-api-key
      app-key: dGVzdC1hcHAta2V5Cg== # test-app-key
