apiVersion: v2
name: argocd-applicationset
description: A Helm chart for installing ArgoCD ApplicationSet
type: application
version: 1.12.0
appVersion: "v0.4.1"
home: https://github.com/argoproj/argo-helm
icon: https://argocd-applicationset.readthedocs.io/en/stable/assets/logo.png
keywords:
  - argoproj
  - appset
  - gitops
maintainers:
  - name: maruina
annotations:
  artifacthub.io/changes: |
    - "[Changed]: updated application version for v0.4.1 and its CRD for support of skipCrds in applications"
    - "[Added]: extraContainers support in Deployment resource"
