{{- if .Values.notifications.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "argo-cd.notifications.fullname" . }}-metrics
  labels:
    {{- include "argo-cd.labels" (dict "context" . "component" .Values.notifications.name "name" .Values.notifications.name) | nindent 4 }}
    {{- with .Values.notifications.metrics.service.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.notifications.metrics.service.annotations  }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    {{- include "argo-cd.selectorLabels" (dict "context" . "component" .Values.notifications.name "name" "notifications-controller") | nindent 6 }}
  ports:
  - name: metrics
    port: {{ .Values.notifications.metrics.port }}
    targetPort: {{ .Values.notifications.metrics.port }}
{{- end }}
