{{- if and .Values.server.enabled .Values.server.backendTLSPolicy.enabled -}}
{{- $fullName := include "argo-workflows.server.fullname" . -}}
apiVersion: gateway.networking.k8s.io/v1
kind: BackendTLSPolicy
metadata:
  name: {{ $fullName }}
  namespace: {{ include "argo-workflows.namespace" . | quote }}
  labels:
    {{- include "argo-workflows.labels" (dict "context" . "component" .Values.server.name "name" .Values.server.name) | nindent 4 }}
    {{- with .Values.server.backendTLSPolicy.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.server.backendTLSPolicy.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  targetRefs:
    {{- with .Values.server.backendTLSPolicy.targetRefs }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.server.backendTLSPolicy.validation }}
  validation:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
