{{- if .Values.server.httproute.enabled -}}
{{- $fullName := include "argo-cd.server.fullname" . -}}
{{- $insecure := index .Values.configs.params "server.insecure" | toString -}}
{{- $servicePortHttp := .Values.server.service.servicePortHttp -}}
{{- $servicePortHttps := .Values.server.service.servicePortHttps -}}
{{- $servicePortHttp2 := .Values.server.service.servicePortHttp2 -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ $fullName }}
  namespace: {{ include  "argo-cd.namespace" . }}
  labels:
    {{- include "argo-cd.labels" (dict "context" . "component" .Values.server.name "name" .Values.server.name) | nindent 4 }}
    {{- with .Values.server.httproute.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.server.httproute.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  parentRefs:
    {{- with .Values.server.httproute.parentRefs }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.server.httproute.hostnames }}
  hostnames:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    {{- range $servicePort := eq $insecure "true" | ternary (list $servicePortHttp $servicePortHttp2) (list $servicePortHttps) -}}
    {{- range $.Values.server.httproute.rules | default (list dict) }}
    - backendRefs:
        - group: ''
          kind: Service
          name: {{ $fullName }}
          port: {{ $servicePort }}
          weight: 1
    {{- with .matches | default (eq $servicePort $servicePortHttp2 | ternary (list dict) list) }}
      matches:
      {{- range . }}
        - {{ eq $servicePort $servicePortHttp2 | ternary (set (deepCopy .) "headers" (prepend (index . "headers" | default list) (dict "name" "Content-Type" "value" "application/grpc"))) . | toYaml | indent 10 | trim }}
      {{- end }}
    {{- end }}
    {{- with .filters }}
      filters:
      {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- end }}
    {{- end }}
{{- end }}
