{{- if .Values.server.additionalProjects }}
apiVersion: v1
kind: List
items:
{{- range .Values.server.additionalProjects }}
  - apiVersion: argoproj.io/v1alpha1
    kind: AppProject
    metadata:
      {{- if .additionalProjects }}
      annotations:
      {{- range $key, $value := .additionalProjects }}
        {{ $key }}: {{ $value | quote }}
      {{- end }}
      {{- end }}
      {{- if .additionalLabels }}
      labels:
{{- toYaml .additionalLabels | nindent 8 }}
      {{- end }}
      name: {{ .name }}
      {{- if .namespace }}
      namespace: {{ .namespace }}
      {{- end }}
    spec:
      description: {{ .description }}
      sourceRepos:
{{- toYaml .sourceRepos | nindent 8 }}
      destinations:
{{- toYaml .destinations | nindent 8 }}
      {{- if .clusterResourceWhitelist }}
      clusterResourceWhitelist:
{{- toYaml .clusterResourceWhitelist | nindent 8 }}
      {{- end }}
      {{- if .namespaceResourceBlacklist }}
      namespaceResourceBlacklist:
{{- toYaml .namespaceResourceBlacklist | nindent 8 }}
      {{- end }}
      {{- if .orphanedResources }}
      orphanedResources:
{{- toYaml .orphanedResources | nindent 8 }}
      {{- end }}
      {{- if .roles }}
      roles:
{{- toYaml .roles | nindent 8 }}
      {{- end }}
{{- end }}
{{- end }}