{{- if .Values.server.route.enabled -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ template "argo-cd.server.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "argo-cd.name" . }}-{{ .Values.server.name }}
    helm.sh/chart: {{ include "argo-cd.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/component: {{ .Values.server.name }}
{{- with .Values.server.route.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  host: {{ .Values.server.route.hostname | quote }}
  to:
    kind: Service
    name: {{ template "argo-cd.server.fullname" . }}
    weight: 100
  port:
    targetPort: https
  tls:
    termination: {{ .Values.server.route.termination_type | default "passthrough" }}
    insecureEdgeTerminationPolicy: {{ .Values.server.route.termination_policy | default "None" }} 
  wildcardPolicy: None
{{- end }}
