apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Values.controller.name}}
  labels:
    app: {{ .Release.Name }}-{{ .Values.controller.name}}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    namespace: {{ .Release.Namespace }}
    heritage: {{ .Release.Service }}
spec:
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Values.controller.name}}
        release: {{ .Release.Name }}
      {{- if .Values.controller.podAnnotations }}
      annotations:
{{ toYaml .Values.controller.podAnnotations | indent 8}}{{- end }}
    spec:
      serviceAccountName: {{ .Values.controller.serviceAccount | quote }}
      containers:
        - name: controller
          image: "{{ .Values.images.namespace }}/{{ .Values.images.controller }}:{{ .Values.images.tag }}"
          command: [ "workflow-controller" ]
          args:
          - "--configmap"
          - "{{ .Release.Name }}-{{ .Values.controller.name}}-configmap"
          - "--loglevel"
          - "{{ .Values.controller.logging.level }}"
          - "--gloglevel"
          - "{{ .Values.controller.logging.globallevel }}"
          env:
          - name: ARGO_NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
