apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-apply-sensor-crd
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-delete-policy: hook-succeeded
spec:
  backoffLimit: 5
  activeDeadlineSeconds: 100
  template:
    spec:
      containers:
      - name: kubectl-apply
        image: lachlanevenson/k8s-kubectl
        command: ["/bin/sh"]
        args: ["-c", 'echo ''{{- include "sensor-crd-json" .}}'' | kubectl apply -f -']
      restartPolicy: Never