apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Values.eventbusController.name }}
  labels:
    app: {{ .Release.Name }}-{{ .Values.eventbusController.name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.eventbusController.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Values.eventbusController.name }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Values.eventbusController.name }}
        release: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount }}
      containers:
        - name: {{ .Values.eventbusController.name }}
          image: "{{ .Values.registry }}/{{ .Values.eventbusController.image }}:{{ .Values.eventbusController.tag }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          {{- if .Values.singleNamespace }}
          args:
            - --namespaced
          {{- end }}
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: NATS_STREAMING_IMAGE
              value: {{ .Values.eventbusController.natsStreamingImage }}
            - name: NATS_METRICS_EXPORTER_IMAGE
              value: {{ .Values.eventbusController.natsMetricsExporterImage }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 3
            periodSeconds: 3
      {{- with .Values.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- if .Values.eventbusController.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.eventbusController.nodeSelector | indent 8 }}
{{- end }}
{{- if .Values.eventbusController.tolerations }}
      tolerations:
{{ toYaml .Values.eventbusController.tolerations | indent 8 }}
{{- end }}
{{- if .Values.eventbusController.affinity }}
      affinity:
{{ toYaml .Values.eventbusController.affinity | indent 8 }}
{{- end }}
