apiVersion: v1
description: A Helm chart to install Argo-Events in k8s Cluster
name: argo-events
version: 0.5.0
keywords:
- argo-events
- sensor-controller
- gateway-controller
sources:
- https://github.com/argoproj/argo-events
maintainers:
- name: Vaibhav Page
- name: Matt Magaldi
appVersion: 0.9.3
icon: https://raw.githubusercontent.com/argoproj/argo/master/argo.png
