apiVersion: v1
description: A Helm chart to install Argo-Events in k8s Cluster
name: argo-events
version: 0.6.1
keywords:
  - argo-events
  - sensor-controller
  - gateway-controller
sources:
  - https://github.com/argoproj/argo-events
maintainers:
  - name: VaibhavPage
  - name: magaldima
appVersion: 0.11
icon: https://raw.githubusercontent.com/argoproj/argo/master/docs/assets/argo.png
home: https://github.com/argoproj/argo-helm
