apiVersion: v2
description: A Helm chart to install Argo-Events in k8s Cluster
name: argo-events
version: 1.4.3
keywords:
  - argo-events
  - sensor-controller
  - eventsource-controller
  - eventbus-controller
sources:
  - https://github.com/argoproj/argo-events
maintainers:
  - name: VaibhavPage
  - name: whynowy
appVersion: 1.3.1
icon: https://raw.githubusercontent.com/argoproj/argo/master/docs/assets/argo.png
home: https://github.com/argoproj/argo-helm
