apiVersion: v2
appVersion: v1.7.4
description: A Helm chart for Argo Events, the event-driven workflow automation framework
name: argo-events
version: 2.0.10
home: https://github.com/argoproj/argo-helm
icon: https://argoproj.github.io/argo-events/assets/logo.png
keywords:
  - argoproj
  - argo-events
sources:
  - https://github.com/argoproj/argo-events
maintainers:
  - name: argoproj
    url: https://argoproj.github.io/
annotations:
  artifacthub.io/changes: |
    - "[Changed]: Upgrade Argo events controller to v1.7.4"
