apiVersion: v2
description: A Helm chart to install Argo-Events in k8s Cluster
name: argo-events
version: 1.8.0
keywords:
  - argo-events
  - sensor-controller
  - eventsource-controller
  - eventbus-controller
sources:
  - https://github.com/argoproj/argo-events
maintainers:
  - name: VaibhavPage
  - name: whynowy
appVersion: v1.5.0
icon: https://argoproj.github.io/argo-events/assets/logo.png
home: https://github.com/argoproj/argo-helm
annotations:
  artifacthub.io/changes: |
    - "[Changed]: Update to Argo Events v1.5.0"
