apiVersion: v1
description: A Helm chart to install Argo-Events in k8s Cluster
name: argo-events
version: 0.1.0
keywords:
- argo-events
- sensor-controller
sources:
- https://github.com/argoproj/argo-events
maintainers:
- name: Matt Magaldi
  email: mmagaldi@blackrock.com
- name: Vaibhav Page
  email: vpage@blackrock.com
appVersion: 0.1.0
