{{- range $appSetName, $appSetData:= .Values.applicationsets }}
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  {{- with $appSetData.additionalAnnotations }}
  annotations:
    {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
  {{- with $appSetData.additionalLabels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ $appSetName }}
  {{- with $appSetData.namespace }}
  namespace: {{ . }}
  {{- end }}
  {{- with $appSetData.finalizers }}
  finalizers:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if hasKey $appSetData "goTemplate" }}
  goTemplate: {{ $appSetData.goTemplate }}
  {{- end }}
  {{- with $appSetData.generators }}
  generators:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $appSetData.ignoreApplicationDifferences }}
  ignoreApplicationDifferences:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $appSetData.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $appSetData.syncPolicy }}
  syncPolicy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $appSetData.template }}
  template:
    {{- with .metadata }}
    metadata:
      {{- with .annotations }}
      annotations:
        {{- range $key, $value := . }}
        {{ $key }}: {{ $value | squote }}
        {{- end }}
      {{- end }}
      {{- with .labels }}
      labels:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      name: {{ .name | squote }}
      {{- with .namespace }}
      namespace: {{ . | squote }}
      {{- end }}
    {{- end }}
    {{- with .spec }}
    spec:
      project: {{ .project | squote }}
      {{- with .source }}
      source:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .sources }}
      sources:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      destination:
        {{- toYaml .destination | nindent 8 }}
      {{- with .syncPolicy }}
      syncPolicy:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .ignoreDifferences }}
      ignoreDifferences:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .info }}
      info:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- end -}}
  {{- end }}
  {{- with $appSetData.templatePatch }}
  templatePatch: |
    {{- . | nindent 4 }}
  {{- end }}
{{- end }}
