imageNamespace: argoproj
ciImage: argoci
imageTag: v1.0.0-alpha1

argo:
  imagesNamespace: argoproj
  imagesTag: v2.0.0-alpha3
  enableWebConsole: false
  installMinio: true
  minioBucketName: argo-artifacts
  useReleaseAsInstanceID: true
