{{- $redisHa := (index .Values "redis-ha") -}}
{{- if and .Values.redis.enabled (not $redisHa.enabled) -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "argo-cd.redis.fullname" . }}
  labels:
    {{- include "argo-cd.labels" (dict "context" . "component" .Values.redis.name "name" .Values.redis.name) | nindent 4 }}
    app.kubernetes.io/version: {{ .Values.redis.image.tag | quote }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "argo-cd.name" . }}-{{ .Values.redis.name }}
  template:
    metadata:
      {{- with (mergeOverwrite (deepCopy .Values.global.podAnnotations) .Values.redis.podAnnotations) }}
      annotations:
        {{- range $key, $value := . }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
      {{- end }}
      labels:
        {{- include "argo-cd.labels" (dict "context" . "component" .Values.redis.name "name" .Values.redis.name) | nindent 8 }}
        app.kubernetes.io/version: {{ .Values.redis.image.tag | quote }}
        {{- with (mergeOverwrite (deepCopy .Values.global.podLabels) .Values.redis.podLabels) }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.redis.imagePullSecrets | default .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      automountServiceAccountToken: {{ .Values.redis.serviceAccount.automountServiceAccountToken }}
      serviceAccountName: {{ template "argo-cd.redisServiceAccountName" . }}
      {{- if .Values.redis.securityContext }}
      securityContext: {{- toYaml .Values.redis.securityContext | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ template "argo-cd.redis.fullname" . }}
        args:
        - --save
        - ""
        - --appendonly
        - "no"
        {{- with .Values.redis.extraArgs }}
        {{- . | toYaml | nindent 8 }}
        {{- end }}
        image: {{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}
        imagePullPolicy: {{ .Values.redis.image.imagePullPolicy}}
        {{- if .Values.redis.containerSecurityContext }}
        securityContext: {{- toYaml .Values.redis.containerSecurityContext | nindent 10 }}
        {{- end }}
        {{- if .Values.redis.env }}
        env:
{{- toYaml .Values.redis.env | nindent 8 }}
        {{- end }}
        {{- with .Values.redis.envFrom }}
        envFrom: {{- toYaml . | nindent 8 }}
        {{- end }}
        ports:
        - containerPort: {{ .Values.redis.containerPort }}
          name: redis
{{- if .Values.redis.volumeMounts }}
        volumeMounts:
{{- toYaml .Values.redis.volumeMounts | nindent 10 }}
{{- end }}
        resources:
{{- toYaml .Values.redis.resources | nindent 10 }}
      {{- if .Values.redis.metrics.enabled }}
      - name: metrics
        env:
        - name: REDIS_ADDR
          value: {{ printf "redis://localhost:%v" .Values.redis.containerPort }}
        - name: REDIS_EXPORTER_WEB_LISTEN_ADDRESS
          value: {{ printf "0.0.0.0:%v" .Values.redis.metrics.containerPort }}
        image: {{ .Values.redis.metrics.image.repository }}:{{ .Values.redis.metrics.image.tag }}
        imagePullPolicy: {{ .Values.redis.metrics.image.imagePullPolicy}}
        ports:
        - containerPort: {{ .Values.redis.metrics.containerPort }}
          name: metrics
          protocol: TCP
        resources: {{- toYaml .Values.redis.metrics.resources | nindent 10 }}
        {{- with .Values.redis.containerSecurityContext }}
        securityContext: {{- toYaml . | nindent 10 }}
        {{- end }}
      {{- end }}
    {{- with .Values.redis.extraContainers }}
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- if .Values.redis.nodeSelector }}
      nodeSelector:
{{- toYaml .Values.redis.nodeSelector | nindent 8 }}
    {{- end }}
    {{- if .Values.redis.tolerations }}
      tolerations:
{{- toYaml .Values.redis.tolerations | nindent 8 }}
    {{- end }}
    {{- if .Values.redis.affinity }}
      affinity:
{{- toYaml .Values.redis.affinity | nindent 8 }}
    {{- end }}
    {{- with .Values.redis.topologySpreadConstraints }}
      topologySpreadConstraints:
      {{- range $constraint := . }}
      - {{ toYaml $constraint | nindent 8 | trim }}
        {{- if not $constraint.labelSelector }}
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: {{ include "argo-cd.name" $ }}-{{ $.Values.redis.name }}
        {{- end }}
      {{- end }}
    {{- end }}
{{- if .Values.redis.volumes }}
      volumes:
{{- toYaml .Values.redis.volumes | nindent 8}}
{{- end }}
      {{- if .Values.redis.initContainers }}
      initContainers:
      {{- toYaml .Values.redis.initContainers | nindent 6 }}
      {{- end }}
{{- if .Values.redis.priorityClassName }}
      priorityClassName: {{ .Values.redis.priorityClassName }}
{{- end }}
{{- end }}
