{{- $redisHa := (index .Values "redis-ha") -}}
{{- if and .Values.redis.enabled (not $redisHa.enabled) -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "argo-cd.redis.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "argo-cd.name" . }}-{{ .Values.redis.name }}
    helm.sh/chart: {{ include "argo-cd.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/component: {{ .Values.redis.name }}
    app.kubernetes.io/version: {{ .Values.redis.image.tag }}    
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "argo-cd.name" . }}-{{ .Values.redis.name }}
  template:
    metadata:
      {{- if .Values.redis.podAnnotations }}
      annotations:
      {{- range $key, $value := .Values.redis.podAnnotations }}
        {{ $key }}: {{ $value | quote }}
      {{- end }}
      {{- end }}
      labels:
        app.kubernetes.io/name: {{ include "argo-cd.name" . }}-{{ .Values.redis.name }}
        helm.sh/chart: {{ include "argo-cd.chart" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/part-of: argocd
        app.kubernetes.io/component: {{ .Values.redis.name }}
        app.kubernetes.io/version: {{ .Values.redis.image.tag }}
        {{- if .Values.redis.podLabels }}
{{- toYaml .Values.redis.podLabels | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      automountServiceAccountToken: false
      {{- if .Values.redis.securityContext }}
      securityContext: {{- toYaml .Values.redis.securityContext | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ template "argo-cd.redis.fullname" . }}
        args:
        - --save
        - ""
        - --appendonly
        - "no"
        image: {{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}
        imagePullPolicy: {{ .Values.redis.image.imagePullPolicy}}
        {{- if .Values.redis.containerSecurityContext }}
        securityContext: {{- toYaml .Values.redis.containerSecurityContext | nindent 10 }}
        {{- end }}          
        {{- if .Values.redis.env }}
        env:
{{- toYaml .Values.redis.env | nindent 8 }}
        {{- end }}
        ports:
        - containerPort: {{ .Values.redis.containerPort }}
{{- if .Values.redis.volumeMounts }}

        volumeMounts:
{{- toYaml .Values.redis.volumeMounts | nindent 10 }}
{{- end }}
        resources:
{{- toYaml .Values.redis.resources | nindent 10 }}
    {{- if .Values.redis.nodeSelector }}
      nodeSelector:
{{- toYaml .Values.redis.nodeSelector | nindent 8 }}
    {{- end }}
    {{- if .Values.redis.tolerations }}
      tolerations:
{{- toYaml .Values.redis.tolerations | nindent 8 }}
    {{- end }}
    {{- if .Values.redis.affinity }}
      affinity:
{{- toYaml .Values.redis.affinity | nindent 8 }}
    {{- end }}
{{- if .Values.redis.volumes }}
      volumes:
{{- toYaml .Values.redis.volumes | nindent 8}}
{{- end }}
{{- if .Values.redis.priorityClassName }}
      priorityClassName: {{ .Values.redis.priorityClassName }}
{{- end }}
{{- end }}
