{{- if .Values.controller.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "argo-rollouts.fullname" . }}
  labels:
    app.kubernetes.io/component: server
    {{- include "argo-rollouts.labels" . | nindent 4 }}
    {{- range $key, $value := .Values.controller.metrics.serviceMonitor.additionalLabels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- with .Values.controller.metrics.serviceMonitor.additionalAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  endpoints:
  - port: metrics
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app.kubernetes.io/component: server
      {{- include "argo-rollouts.selectorLabels" . | nindent 6 }}
{{- end }}
