{{ if .Values.cm.create }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "argocd-notifications.configMapName" . }}
  labels:
    {{- include "argocd-notifications.labels" . | nindent 4 }}
data:
  context: |
    argocdUrl: {{ .Values.argocdUrl | quote }}
  {{- with .Values.context }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.notifiers }}
    {{- toYaml . | nindent 2 }}
  {{- end }}
  {{- with .Values.subscriptions }}
  subscriptions: |
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.templates }}
    {{- toYaml . | nindent 2 }}
  {{- end }}
  {{- with .Values.triggers }}
    {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}
