apiVersion: apps/v1
kind: Deployment
metadata:
  {{- with (mergeOverwrite (deepCopy .Values.global.deploymentAnnotations) .Values.controller.deploymentAnnotations) }}
  annotations:
    {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
  name: {{ include "argo-rollouts.fullname" . }}
  namespace: {{ include "argo-rollouts.namespace" . | quote }}
  labels:
  {{- range $key, $value := (mergeOverwrite (deepCopy .Values.global.deploymentLabels) .Values.controller.deploymentLabels) }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
    app.kubernetes.io/component: {{ .Values.controller.component }}
    {{- include "argo-rollouts.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: {{ .Values.controller.component }}
      {{- include "argo-rollouts.selectorLabels" . | nindent 6 }}
  strategy:
    type: RollingUpdate
  replicas: {{ .Values.controller.replicas }}
  revisionHistoryLimit: {{ .Values.global.revisionHistoryLimit }}
  template:
    metadata:
      annotations:
        {{- with (mergeOverwrite (deepCopy .Values.podAnnotations) .Values.controller.podAnnotations) }}
        {{- range $key, $value := . }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
        {{- end }}
        checksum/cm: {{ include (print $.Template.BasePath "/controller/configmap.yaml") . | sha256sum }}
      labels:
        {{- include "argo-rollouts.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: {{ .Values.controller.component }}
        {{- range $key, $value := (mergeOverwrite (deepCopy .Values.podLabels) .Values.controller.podLabels) }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "argo-rollouts.serviceAccountName" . }}
      containers:
      - image: "{{ .Values.controller.image.registry }}/{{ .Values.controller.image.repository }}:{{ default .Chart.AppVersion .Values.controller.image.tag }}"
        args:
        - --healthzPort={{ .Values.controller.containerPorts.healthz }}
        - --metricsport={{ .Values.controller.containerPorts.metrics }}
        - "--loglevel={{ .Values.controller.logging.level }}"
        - "--logformat={{ .Values.controller.logging.format }}"
        - "--kloglevel={{ .Values.controller.logging.kloglevel }}"
        {{- if not .Values.clusterInstall }}
        - --namespaced
        {{- end }}
        {{- if gt (int .Values.controller.replicas) 1 }}
        - --leader-elect
        {{- end }}
        {{- with .Values.controller.extraArgs }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.controller.extraEnv }}
        env:
          {{- toYaml . | nindent 8 }}
        {{- end }}
        imagePullPolicy: {{ .Values.controller.image.pullPolicy }}
        name: argo-rollouts
        ports:
        - containerPort: {{ .Values.controller.containerPorts.metrics }}
          name: metrics
        - containerPort: {{ .Values.controller.containerPorts.healthz }}
          name: healthz
        livenessProbe:
          {{- toYaml .Values.controller.livenessProbe | nindent 10 }}
        readinessProbe:
          {{- toYaml .Values.controller.readinessProbe | nindent 10 }}
        securityContext:
          {{- toYaml .Values.containerSecurityContext | nindent 10 }}
        {{- with .Values.controller.lifecycle }}
        lifecycle: {{ toYaml . | nindent 10 }}
        {{- end }}
        resources:
          {{- toYaml .Values.controller.resources | nindent 10 }}
        volumeMounts:
        - name: plugin-bin
          mountPath: /home/argo-rollouts/plugin-bin
        - name: tmp
          mountPath: /tmp
        {{- with .Values.controller.volumeMounts }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.controller.extraContainers }}
        {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- with .Values.controller.initContainers }}
      initContainers:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.controller.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.controller.nodeSelector | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- with .Values.controller.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ . }}
      {{- end }}
      {{- if .Values.controller.tolerations }}
      tolerations:
        {{- toYaml .Values.controller.tolerations | nindent 8 }}
      {{- end }}
      {{- with .Values.global.dnsConfig }}
      dnsConfig:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.controller.affinity }}
      affinity:
        {{- toYaml .Values.controller.affinity | nindent 8 }}
      {{- end }}
      {{- with .Values.controller.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- range $constraint := . }}
      - {{ toYaml $constraint | nindent 8 | trim }}
        {{- if not $constraint.labelSelector }}
        labelSelector:
          matchLabels:
            app.kubernetes.io/component: {{ $.Values.controller.component }}
            {{- include "argo-rollouts.selectorLabels" $ | nindent 12 }}
        {{- end }}
        {{- end }}
      {{- end }}
      {{- with .Values.controller.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      volumes:
      - name: plugin-bin
        emptyDir: {}
      - name: tmp
        emptyDir: {}
      {{- with .Values.controller.volumes }}
        {{- toYaml . | nindent 6 }}
      {{- end }}
