{{- if .Values.controller.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "argo-rollouts.fullname" . }}-metrics
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/component: {{ .Values.controller.component }}
    {{- include "argo-rollouts.labels" . | nindent 4 }}
  {{- with .Values.serviceAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ports:
  - name: {{ .Values.controller.metrics.service.portName }}
    protocol: TCP
    port: {{ .Values.controller.metrics.service.port }}
    targetPort: metrics
  selector:
    app.kubernetes.io/component: {{ .Values.controller.component }}
    {{- include "argo-rollouts.selectorLabels" . | nindent 4 }}
{{- end }}
