{{- if .Values.config.argocd.token }}
apiVersion: v1
kind: Secret
metadata:
  name: argocd-image-updater-secret
type: Opaque
data: 
  argocd.token: {{ .Values.config.argocd.token | b64enc }}
{{- end }}
