{{- if .Values.config.argocd.token }}
apiVersion: v1
kind: Secret
metadata:
  name: argocd-image-updater-secret
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "argocd-image-updater.labels" . | nindent 4 }}
type: Opaque
data:
  argocd.token: {{ .Values.config.argocd.token | b64enc }}
{{- end }}
