apiVersion: v2
name: argo-workflows
description: A Helm chart for Argo Workflows
type: application
version: 0.16.1
appVersion: v3.3.6
icon: https://raw.githubusercontent.com/argoproj/argo-workflows/master/docs/assets/argo.png
home: https://github.com/argoproj/argo-helm
sources:
  - https://github.com/argoproj/argo-workflows
maintainers:
  - name: alexec
  - name: alexmt
  - name: jessesuen
  - name: benjaminws
annotations:
  artifacthub.io/changes: |
    - "[Changed]: Update to app version v3.3.6"
