apiVersion: v2
appVersion: v3.3.9
name: argo-workflows
description: A Helm chart for Argo Workflows
type: application
version: 0.17.2
icon: https://raw.githubusercontent.com/argoproj/argo-workflows/master/docs/assets/argo.png
home: https://github.com/argoproj/argo-helm
sources:
  - https://github.com/argoproj/argo-workflows
maintainers:
  - name: argoproj
    url: https://argoproj.github.io/
annotations:
  artifacthub.io/changes: |
    - "[Changed]: Helm chart maintainers standardized to argoproj"
