apiVersion: v2
name: argo-workflows
description: A Helm chart for Argo Workflows
type: application
version: 0.12.0
appVersion: v3.2.9
icon: https://raw.githubusercontent.com/argoproj/argo-workflows/master/docs/assets/argo.png
home: https://github.com/argoproj/argo-helm
sources:
  - https://github.com/argoproj/argo-workflows
maintainers:
  - name: alexec
  - name: alexmt
  - name: jessesuen
  - name: benjaminws
annotations:
  artifacthub.io/changes: |
    - "[Added]: Add parameter for enabling roles."
