apiVersion: v2
appVersion: v3.6.2
name: argo-workflows
description: A Helm chart for Argo Workflows
type: application
version: 0.45.2
icon: https://argo-workflows.readthedocs.io/en/stable/assets/logo.png
home: https://github.com/argoproj/argo-helm
sources:
  - https://github.com/argoproj/argo-workflows
maintainers:
  - name: argoproj
    url: https://argoproj.github.io/
annotations:
  artifacthub.io/signKey: |
    fingerprint: 2B8F22F57260EFA67BE1C5824B11F800CD9D2252
    url: https://argoproj.github.io/argo-helm/pgp_keys.asc
  artifacthub.io/changes: |
    - kind: fixed
      description: Reference to ingress link was fixed
