apiVersion: v2
name: argo-workflows
description: A Helm chart for Argo Workflows
type: application
version: 0.2.13
appVersion: "v3.0.7"
icon: https://raw.githubusercontent.com/argoproj/argo-workflows/master/docs/assets/argo.png
home: https://github.com/argoproj/argo-helm
sources:
  - https://github.com/argoproj/argo-workflows
maintainers:
  - name: alexec
  - name: alexmt
  - name: jessesuen
  - name: benjaminws
annotations:
  artifacthub.io/changes: |
    - "[Changed]: Argo workflows values file no longer has examples referencing ArgoCD"
    - "[Added]: pathType variable now available for ingress template"
