apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
  labels:
    app.kubernetes.io/name: {{ include "argo-cd.name" . }}-repo-server
    helm.sh/chart: {{ include "argo-cd.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: {{ include "argo-cd.name" . }}
    app.kubernetes.io/component: repo-server
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "argo-cd.name" . }}-repo-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "argo-cd.name" . }}-repo-server
        helm.sh/chart: {{ include "argo-cd.chart" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/part-of: {{ include "argo-cd.name" . }}
        app.kubernetes.io/component: repo-server
    spec:
      automountServiceAccountToken: false
      containers:
      - name: argocd-repo-server
        image: {{ .Values.repoServer.image.repository }}:{{ .Values.repoServer.image.tag }}
        imagePullPolicy: {{ .Values.repoServer.image.pullPolicy}}
        command: [argocd-repo-server]
        ports:
        - containerPort: {{ .Values.repoServer.containerPort }}
        livenessProbe:
          initialDelaySeconds: 5
          periodSeconds: 10
          tcpSocket:
            port: {{ .Values.repoServer.containerPort }}
        readinessProbe:
          tcpSocket:
            port: {{ .Values.repoServer.containerPort }}
          initialDelaySeconds: 5
          periodSeconds: 10
        volumeMounts:
        - mountPath: /app/config/ssh
          name: ssh-known-hosts
        - mountPath: /app/config/tls
          name: tls-certs
        {{- if .Values.repoServer.volumeMounts }}
        {{ toYaml .Values.repoServer.volumeMounts | nindent 8 | trim }}
        {{- end }}
      volumes:
      - configMap:
          name: argocd-ssh-known-hosts-cm
        name: ssh-known-hosts
      - configMap:
          name: argocd-tls-certs-cm
        name: tls-certs
      {{- if .Values.repoServer.volumes }}
      {{ toYaml .Values.repoServer.volumes | nindent 6 | trim }}
      {{- end }}
